<%  # This file contains ERB-interpreted YAML directives for testkitchen.
    # Secrets are read from the local execution ENV into this file, and
    # passed to the Chef tests via node attributes applied to the test suites.
    
# To keep the YAML as simple as possible, some values are computed here
# Set your primary AWS credentials for accessing your detailed billing files from S3
ICE_AWS_ACCESS_KEY_ID = ENV['ICE_AWS_ACCESS_KEY_ID']
ICE_AWS_ACCESS_KEY_SECRET = ENV['ICE_AWS_ACCESS_KEY_SECRET']

# I set account name=>id mappings in my environment variables as well.
# These variables are used for when you have multiple accounts and want 
# to query them with friendly names in ice.
ICE_ACCOUNT1_NAME = ENV['ICE_ACCOUNT1_NAME']
ICE_ACCOUNT1_NUMBER = ENV['ICE_ACCOUNT1_NUMBER']

ICE_ACCOUNT2_NAME = ENV['ICE_ACCOUNT2_NAME']
ICE_ACCOUNT2_NUMBER = ENV['ICE_ACCOUNT2_NUMBER']

%>
---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    customize:
      memory: 1024
  attributes:
    ice:
      version: 0.0.2
      war_url: https://s3.amazonaws.com/ice-app
      skip_manifest_check: true
      checksum: c5f0c31d8493783814c017a2af575e8d8fa1855359008b868621823381d61d6a 
      company_name: Your Company
      billing_aws_access_key_id: <%= ICE_AWS_ACCESS_KEY_ID %>
      billing_aws_secret_key: <%= ICE_AWS_ACCESS_KEY_SECRET %>
      billing_s3_bucket_name: billing_bucket_name
      billing_s3_bucket_prefix: billing_bucket_prefix_if_any/
      work_s3_bucket_name: work_bucket_name
      work_s3_bucket_prefix: work_bucket_prefix_if_any/
      start_millis: 1367380800000
      # The following settings are only required for dealing with multiple AWS accounts
      accounts: { <%= ICE_ACCOUNT1_NAME %>: <%= ICE_ACCOUNT1_NUMBER %>, 
            <%= ICE_ACCOUNT2_NAME %>: <%= ICE_ACCOUNT2_NUMBER %>,
            <%= ICE_ACCOUNT3_NAME %>: <%= ICE_ACCOUNT3_NUMBER %>
            }
      owner_account: account1
      linked_accounts: [ account2,account3 ]
    
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
    customize:
      memory: 1024
  attributes:
    ice:
      version: 0.0.2
      war_url: https://s3.amazonaws.com/ice-app
      skip_manifest_check: true
      checksum: c5f0c31d8493783814c017a2af575e8d8fa1855359008b868621823381d61d6a 
      company_name: Your Company
      billing_aws_access_key_id: <%= ICE_AWS_ACCESS_KEY_ID %>
      billing_aws_secret_key: <%= ICE_AWS_ACCESS_KEY_SECRET %>
      billing_s3_bucket_name: billing_bucket_name
      billing_s3_bucket_prefix: billing_bucket_prefix_if_any/
      work_s3_bucket_name: work_bucket_name
      work_s3_bucket_prefix: work_bucket_prefix_if_any/
      start_millis: 1367380800000
      # The following settings are only required for dealing with multiple AWS accounts
      accounts: { <%= ICE_ACCOUNT1_NAME %>: <%= ICE_ACCOUNT1_NUMBER %>, 
            <%= ICE_ACCOUNT2_NAME %>: <%= ICE_ACCOUNT2_NUMBER %>,
            <%= ICE_ACCOUNT3_NAME %>: <%= ICE_ACCOUNT3_NUMBER %>
            }
      owner_account: account1
      linked_accounts: [ account2,account3 ]
