<%  # This file contains ERB-interpreted YAML directives for testkitchen.
    # Secrets are read from the local execution ENV into this file, and
    # passed to the Chef tests via node attributes applied to the test suites.

# To keep the YAML as simple as possible, some values are computed here
AWS_ACCESS_KEY_ID = ENV['ICE_AWS_ACCESS_KEY_ID'] ||'ice_billing_aws_access_key_id'
AWS_ACCESS_KEY_SECRET = ENV['ICE_AWS_ACCESS_KEY_SECRET'] || 'ice_billing_aws_secret_key'
%>
---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    customize:
      memory: 1024

- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
    customize:
      memory: 1024

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[ice]
  - recipe[ice_cookbook_test]
  attributes:
    ice:
      version: 0.0.2
      war_url: https://s3.amazonaws.com/ice-app
      skip_manifest_check: true
      checksum: c5f0c31d8493783814c017a2af575e8d8fa1855359008b868621823381d61d6a 
      company_name: Your Company
      billing_aws_access_key_id: <%= AWS_ACCESS_KEY_ID %>
      billing_aws_secret_key: <%= AWS_ACCESS_KEY_SECRET %>
      billing_s3_bucket_name: kitchen-tests
      work_s3_bucket_name: kitchen-tests
      billing_s3_bucket_prefix: ice-cookbook-tests-billing-<%= ENV['USER'] %>/
      work_s3_bucket_prefix: ice-cookbook-tests-work-<%= ENV['USER'] %>/
      start_millis: 1367380800000
