AllCops:
  DisplayCopNames: true
  Exclude:
    - vendor/**

ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
NumericLiterals:
  Enabled: false

Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

Metrics/BlockLength:
  Enabled: false
